<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Rank;
use App\Models\Restaurant;

class RestaurantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rankIds = Rank::orderBy('rank', 'asc')->pluck('rank', 'genre_name');
        $insertData = [
            'sushi' => [
                1 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => '寿司 勇',
                    'nearest_station' => '乃木坂駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '西麻布1丁目4-15',
                    'website' => 'http://sushiyuu.com/',
                    'file_name' => 'sushi.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => '鮨 やじま',
                    'nearest_station' => '渋谷駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '東１丁目２６−３１ 大島ビル Ｂ１Ｆ',
                    'website' => 'https://maps.app.goo.gl/bWid3MDaFaKPBSTX8',
                    'file_name' => 'sushi.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => 'すし匠',
                    'nearest_station' => '四谷駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '四谷１丁目１１ 陽臨堂ビル 1F',
                    'website' => 'https://maps.app.goo.gl/ZpzGKW5xqVXbyTzk7',
                    'file_name' => 'sushi.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => '日本橋 蛎殻町 すぎた',
                    'nearest_station' => '水天宮前駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '日本橋蛎殻町１丁目３３−６ ビューハイツ日本橋 地下１階',
                    'website' => 'https://omakase.in/r/fa131638',
                    'file_name' => 'sushi.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => '寿司大',
                    'nearest_station' => 'ゆりかもめ市場前駅',
                    'prefecture' => '東京都',
                    'city' => '江東区',
                    'street' => '豊洲６丁目５−１',
                    'website' => 'https://ge3w100.gorp.jp/',
                    'file_name' => 'sushi.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => '鮨 銀座 おのでら 総本店',
                    'nearest_station' => '東銀座駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '銀座５丁目１４−１４ サンリット銀座ビルIII 2F',
                    'website' => 'https://onodera-group.com/sushi-ginza/',
                    'file_name' => 'sushi.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => '築地すし兆 本店',
                    'nearest_station' => '築地駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '築地３丁目１０−９',
                    'website' => 'https://www.chiyoda-sushi.co.jp/',
                    'file_name' => 'sushi.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => '鮨一新',
                    'nearest_station' => '溜池山王駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '区赤坂２丁目５−６',
                    'website' => 'http://www.its-kenpo.or.jp/fuzoku/restaurant/sushi/index.html',
                    'file_name' => 'sushi.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => '築地青空三代目 本店',
                    'nearest_station' => '築地駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '築地４丁目１３−８ トラスト築地ＫＮビル 1F トラスト',
                    'website' => 'https://tsukijiaozorasandaime-honten.gorp.jp/',
                    'file_name' => 'sushi.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['寿司'],
                    'name' => '鮨 さいとう',
                    'nearest_station' => '六本木一丁目駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '六本木１丁目４−５ アークヒルズ サウスタワー 1F',
                    'website' => 'https://maps.app.goo.gl/MnpC1Zcf9eLm9xDY8',
                    'file_name' => 'sushi.jpg',
                ],
            ],
            'ramen' => [
                1 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => 'ラーメン龍の家',
                    'nearest_station' => '西武新宿駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '西新宿７丁目４−５ 富士野ビル1F',
                    'website' => 'https://www.tatsunoya.net/',
                    'file_name' => 'ramen.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => '麺やいま村',
                    'nearest_station' => '巣鴨駅',
                    'prefecture' => '東京都',
                    'city' => '豊島区',
                    'street' => '巣鴨１丁目１３−３ 福沢ビル',
                    'website' => 'https://menya-imamura.com/',
                    'file_name' => 'ramen.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => 'すごい煮干ラーメン凪 新宿ゴールデン街店本館',
                    'nearest_station' => '新宿三丁目駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '歌舞伎町１丁目１−１０ 2F',
                    'website' => 'https://n-nagi.com/',
                    'file_name' => 'ramen.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => '風雲児',
                    'nearest_station' => '新宿駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '代々木２丁目１４−３ 北斗第一ビル １F',
                    'website' => 'https://www.fu-unji.com/',
                    'file_name' => 'ramen.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => 'ラーメン二郎 三田本店',
                    'nearest_station' => '田町駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '三田２丁目１６−４',
                    'website' => 'https://maps.app.goo.gl/hLMzogmdXXf16bEX7',
                    'file_name' => 'ramen.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => '青島食堂 秋葉原店',
                    'nearest_station' => '岩本町駅',
                    'prefecture' => '東京都',
                    'city' => '千代田区',
                    'street' => '神田佐久間町３丁目２０−１',
                    'website' => 'http://www.aoshima-ramen.co.jp/',
                    'file_name' => 'ramen.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => '博多長浜らーめん 田中商店',
                    'nearest_station' => '六町駅',
                    'prefecture' => '東京都',
                    'city' => '足立区',
                    'street' => '一ツ家２丁目１４−６ アンスリューム 1F',
                    'website' => 'https://www.tanaka-shoten.net/',
                    'file_name' => 'ramen.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => '創作麺工房 鳴龍',
                    'nearest_station' => '新大塚駅',
                    'prefecture' => '東京都',
                    'city' => '豊島区',
                    'street' => '南大塚２丁目３４−４ ＳＫＹ南大塚 １F',
                    'website' => 'https://gf8f400.gorp.jp/',
                    'file_name' => 'ramen.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => '銀座 篝 本店',
                    'nearest_station' => '銀座駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '銀座６丁目４−１２',
                    'website' => 'https://ginzakagari.thebase.in/',
                    'file_name' => 'ramen.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['ラーメン'],
                    'name' => 'スパイス・ラー麺 卍力 西葛西本店',
                    'nearest_station' => '西葛西駅',
                    'prefecture' => '東京都',
                    'city' => '江戸川区',
                    'street' => '西葛西３丁目１６−５',
                    'website' => 'https://ramenmanriki.com/',
                    'file_name' => 'ramen.jpg',
                ],
            ],
            'sashimi' => [
                1 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => '北海道海鮮・個室情緒 ～ ２３番地 ～ 新宿東口店',
                    'nearest_station' => '新宿駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '新宿3-21-4 第2サンパークビル 6Ｆ',
                    'website' => 'https://twitter.com/shinjuku_2332',
                    'file_name' => 'sashimi.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => 'なきざかな 新宿店はなれ',
                    'nearest_station' => '新宿駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '西新宿1-19-13 青鈴ビル 2F',
                    'website' => 'http://www.48gyojyou.com/shop/1215/',
                    'file_name' => 'sashimi.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => 'なきざかな',
                    'nearest_station' => '飯田橋駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '神楽坂5-35 おおとりビル B1F',
                    'website' => 'http://www.48gyojyou.com/shop/4556/',
                    'file_name' => 'sashimi.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => '焼うお いし川',
                    'nearest_station' => '築地駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '築地4-13-5 1',
                    'website' => 'https://www.youtube.com/watch?v=4A-XJ6_GIpI&t=4s',
                    'file_name' => 'sashimi.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => '魚金 本店',
                    'nearest_station' => '新橋駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '新橋3-18-3 第２富士ビル',
                    'website' => 'http://www.uokingroup.jp/',
                    'file_name' => 'sashimi.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => 'なきざかな 新宿店',
                    'nearest_station' => '新宿駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '新宿3-35-10 ローヤルプリンスビル B1',
                    'website' => 'http://www.48gyojyou.com/shop/1200/',
                    'file_name' => 'sashimi.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => '銀座さかなさま',
                    'nearest_station' => '銀座一丁目駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '銀座1-5-10 銀座ファーストファイブビル 5',
                    'website' => 'https://ginzasakanasama.gorp.jp/',
                    'file_name' => 'sashimi.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => '築地もったいない プロジェクト 魚治',
                    'nearest_station' => '有楽町駅',
                    'prefecture' => '東京都',
                    'city' => '千代田区',
                    'street' => '丸の内3-3-1 新東京ビル B1F',
                    'website' => 'http://www.mugen-c.jp/',
                    'file_name' => 'sashimi.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => '魚真 乃木坂店',
                    'nearest_station' => '乃木坂駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '赤坂9-6-32',
                    'website' => 'http://www.uoshins.com/',
                    'file_name' => 'sashimi.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['刺身'],
                    'name' => '都民酒場魚金',
                    'nearest_station' => '五反田駅',
                    'prefecture' => '東京都',
                    'city' => '品川区',
                    'street' => '東五反田2-2-2 松楽ビル Ｂ１Ｆ',
                    'website' => 'http://uokingroup.jp/',
                    'file_name' => 'sashimi.jpg',
                ],
            ],
            'tenpura' => [
                1 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => '天ぷらいちかわ',
                    'nearest_station' => '浅草駅',
                    'prefecture' => '東京都',
                    'city' => '台東区',
                    'street' => '千束１丁目１−１２',
                    'website' => 'https://tempra.xn--6g3a1z.net/',
                    'file_name' => 'tenpura.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => '天ぷら 銀座おのでら 並木通り店',
                    'nearest_station' => '東銀座駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '銀座８丁目５−１０ 金成ビル 6F',
                    'website' => 'https://onodera-group.com/tempura-ginza/',
                    'file_name' => 'tenpura.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => 'てんぷら 下村',
                    'nearest_station' => '新御徒町駅',
                    'prefecture' => '東京都',
                    'city' => '台東区',
                    'street' => '三筋１丁目１１−１３ 1F',
                    'website' => 'https://r.gnavi.co.jp/7m8mddkm0000/',
                    'file_name' => 'tenpura.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => '天ぷら元吉 的場',
                    'nearest_station' => '外苑前駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '南青山３丁目２−４ BA セントラル青山ＮＯ６',
                    'website' => 'http://www.motoyoshi-1120.com/',
                    'file_name' => 'tenpura.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => '天すけ',
                    'nearest_station' => '高円寺駅',
                    'prefecture' => '東京都',
                    'city' => '杉並区',
                    'street' => '高円寺北３丁目２２−７',
                    'website' => 'https://maps.app.goo.gl/17f1xgtRKivZtK4Y7',
                    'file_name' => 'tenpura.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => 'てんぷら 近藤',
                    'nearest_station' => '銀座駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '銀座５丁目５−１３ 坂口ビル ９F',
                    'website' => 'https://tempura-kondo.com/',
                    'file_name' => 'tenpura.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => '天ぷら 深町',
                    'nearest_station' => '京橋駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '京橋２丁目５−２ Ａ・Ｍ京橋ビル',
                    'website' => 'https://maps.app.goo.gl/cd7AvGSjAbv9ri5U9',
                    'file_name' => 'tenpura.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => '天ぷら 天鈴',
                    'nearest_station' => '本蓮沼駅',
                    'prefecture' => '東京都',
                    'city' => '板橋区',
                    'street' => '小豆沢１丁目６−１６ 天鈴',
                    'website' => 'https://maps.app.goo.gl/CAbQH8siRkY7nrZz5',
                    'file_name' => 'tenpura.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => 'てんぷらと和食 山の上 本店・御茶ノ水',
                    'nearest_station' => '御茶ノ水駅',
                    'prefecture' => '東京都',
                    'city' => '千代田区',
                    'street' => '神田駿河台１丁目１',
                    'website' => 'https://www.yamanoue-hotel.co.jp/tempurayamanoue/',
                    'file_name' => 'tenpura.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['天ぷら'],
                    'name' => 'みや川',
                    'nearest_station' => '表参道駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '南青山６丁目１−６',
                    'website' => 'https://maps.app.goo.gl/uC1uyw42MdDN552q8',
                    'file_name' => 'tenpura.jpg',
                ],
            ],
            'udon' => [
                1 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => '村山満月うどん',
                    'nearest_station' => '立川駅',
                    'prefecture' => '東京都',
                    'city' => '武蔵村山市',
                    'street' => '三ツ木１丁目１２−１０',
                    'website' => 'http://www.mangetsuudon.com/',
                    'file_name' => 'udon.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => '純手打ち讃岐うどん 五郎',
                    'nearest_station' => '錦糸町駅',
                    'prefecture' => '東京都',
                    'city' => '墨田区',
                    'street' => '江東橋１丁目１３−１',
                    'website' => 'https://www.facebook.com/udonkogera/',
                    'file_name' => 'udon.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => '手打ちうどん こげら',
                    'nearest_station' => '小川駅',
                    'prefecture' => '東京都',
                    'city' => '東村山市',
                    'street' => '富士見町２丁目６−７２',
                    'website' => 'https://m.facebook.com/sanukiudon.gorou/',
                    'file_name' => 'udon.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => 'うどんや大門',
                    'nearest_station' => '中野駅',
                    'prefecture' => '東京都',
                    'city' => '中野区',
                    'street' => '中野５丁目５２−１５ B1',
                    'website' => 'https://maps.app.goo.gl/XpqU2nukjUK78qTG7',
                    'file_name' => 'udon.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => 'うどん 丸香',
                    'nearest_station' => '神保町駅',
                    'prefecture' => '東京都',
                    'city' => '千代田区',
                    'street' => '神田小川町３丁目１６−１ ニュー駿河台ビル 1F',
                    'website' => 'https://maps.app.goo.gl/JnAybAcYT6mSaMaB8',
                    'file_name' => 'udon.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => '大地のうどん 東京馬場店',
                    'nearest_station' => '高田馬場駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '高田馬場３丁目２２−１４',
                    'website' => 'http://daichinoudon.com/',
                    'file_name' => 'udon.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => '根津うどん 釜竹',
                    'nearest_station' => '根津駅',
                    'prefecture' => '東京都',
                    'city' => '文京区',
                    'street' => '根津２丁目１４−１８',
                    'website' => 'http://kamachiku.com/',
                    'file_name' => 'udon.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => '自家製さぬきうどんと肉甚三 大門店',
                    'nearest_station' => '大門駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '芝大門２丁目６−１０ コンフォート芝大門',
                    'website' => 'http://udon-jinza.com/',
                    'file_name' => 'udon.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => 'うどん伊呂波',
                    'nearest_station' => '明治神宮前駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '神宮前４丁目２８−２６ 木村ビル １階',
                    'website' => 'https://maps.app.goo.gl/AbkUCanzxbcdkjhFA',
                    'file_name' => 'udon.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['うどん'],
                    'name' => '本格手打ちうどん 笑乃讃',
                    'nearest_station' => '玉川上水駅',
                    'prefecture' => '東京都',
                    'city' => '武蔵村山市',
                    'street' => '三ツ藤１丁目８６−４',
                    'website' => 'https://ameblo.jp/udonenosan/',
                    'file_name' => 'udon.jpg',
                ],
            ],
            'soba' => [
                1 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => '雷庵',
                    'nearest_station' => '渋谷駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '渋谷１丁目４−１３ １階',
                    'website' => 'https://www.tysons.jp/ryan/',
                    'file_name' => 'soba.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => '神田まつや 本店',
                    'nearest_station' => '淡路町駅',
                    'prefecture' => '東京都',
                    'city' => '千代田区',
                    'street' => '神田須田町１丁目１３',
                    'website' => 'http://www.kanda-matsuya.jp/',
                    'file_name' => 'soba.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => '蕎楽亭',
                    'nearest_station' => '飯田橋駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '神楽坂３丁目６ 神楽坂館１階',
                    'website' => 'https://maps.app.goo.gl/nA9kGEFGQEcDMrFC6',
                    'file_name' => 'soba.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => '玄蕎麦 野中',
                    'nearest_station' => '中村橋駅',
                    'prefecture' => '東京都',
                    'city' => '練馬区',
                    'street' => '中村２丁目５−１１',
                    'website' => 'https://maps.app.goo.gl/vkfhMmaRifUgqqPP8',
                    'file_name' => 'soba.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => 'うどん そば 加賀',
                    'nearest_station' => '初台駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '本町１丁目２−３ 松海ビル 1F',
                    'website' => 'https://maps.app.goo.gl/rZFbsdepk3bbvk9R8',
                    'file_name' => 'soba.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => 'そば•うどん 丹三郎',
                    'nearest_station' => '古里駅',
                    'prefecture' => '東京都',
                    'city' => '西多摩郡',
                    'street' => '奥多摩町丹三郎２６０',
                    'website' => 'https://www.instagram.com/tanzaburo/',
                    'file_name' => 'soba.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => '手打そば しながわ翁',
                    'nearest_station' => '北品川駅',
                    'prefecture' => '東京都',
                    'city' => '品川区',
                    'street' => '北品川１丁目８−１４ しながわ翁',
                    'website' => 'https://golden-wave1911.wixsite.com/okina-site',
                    'file_name' => 'soba.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => '更科堀井 麻布十番本店',
                    'nearest_station' => '六本木駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '元麻布３丁目１１−４',
                    'website' => 'https://www.sarashina-horii.com/',
                    'file_name' => 'soba.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => '板蕎麦 香り家 恵比寿店',
                    'nearest_station' => '恵比寿駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '恵比寿４丁目３−１０ センチュリー・パーク 1F',
                    'website' => 'https://www.foodgate.net/shop/kaoriya',
                    'file_name' => 'soba.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['そば'],
                    'name' => '本むら庵 荻窪本店',
                    'nearest_station' => '荻窪駅',
                    'prefecture' => '東京都',
                    'city' => '杉並区',
                    'street' => '上荻２丁目７−１１',
                    'website' => 'https://www.honmura-an.co.jp/',
                    'file_name' => 'soba.jpg',
                ],
            ],
            'okonomiyaki' => [
                1 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => 'お好み焼・鉄板焼 88 パチパチ 有楽町本店',
                    'nearest_station' => '日比谷駅',
                    'prefecture' => '東京都',
                    'city' => '千代田区',
                    'street' => '有楽町1-2-4',
                    'website' => 'http://88-web.net/',
                    'file_name' => 'okonomiyaki.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => '神戸六甲道・ぎゅんた 丸の内店',
                    'nearest_station' => '東京駅',
                    'prefecture' => '東京都',
                    'city' => '千代田区',
                    'street' => '丸の内2-7-2 KITTE 5F',
                    'website' => 'https://salt-group.jp/shop/gyunta_marunouchi/',
                    'file_name' => 'okonomiyaki.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => 'ふわとろ本舗 恵比寿店',
                    'nearest_station' => '恵比寿駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '恵比寿西1-14-3 満栄佐藤ビル　１Ｆ',
                    'website' => 'http://www.rb-syuhari.com/fuwatorohonpo.html',
                    'file_name' => 'okonomiyaki.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => 'お好み焼き もんじゃ 上野 ぐりぐり',
                    'nearest_station' => '湯島駅',
                    'prefecture' => '東京都',
                    'city' => '台東区',
                    'street' => '上野2-2-3 コロンビアビル B1F',
                    'website' => 'https://maps.app.goo.gl/vrCgt4DN1tRTVZsu7',
                    'file_name' => 'okonomiyaki.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => '喃風 池袋駅前店',
                    'nearest_station' => '池袋駅',
                    'prefecture' => '東京都',
                    'city' => '豊島区',
                    'street' => '上南池袋2-27-5 カテイビル　4F',
                    'website' => 'https://heart-earth.com/restaurant/nanpu',
                    'file_name' => 'okonomiyaki.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => 'ごっつい 新橋店',
                    'nearest_station' => '新橋駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '新橋3-16-8 ２Ｆ',
                    'website' => 'https://www.instagram.com/gottsui.521/',
                    'file_name' => 'okonomiyaki.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => '電光石火 渋谷センター街店',
                    'nearest_station' => '渋谷駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '宇田川町32-7 HULIC&New UDAGAWA 9F',
                    'website' => 'https://okonomiyaki-denko-sekka.com/shop/shibuya_centergai/',
                    'file_name' => 'okonomiyaki.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => '広島焼 HIDE坊 神田店',
                    'nearest_station' => '神田駅',
                    'prefecture' => '東京都',
                    'city' => '千代田区',
                    'street' => '鍛冶町2-9-17 １Ｆ',
                    'website' => 'http://www.hideboukanda.com/',
                    'file_name' => 'okonomiyaki.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => '広島風お好み 鉄板焼き 友',
                    'nearest_station' => '西武新宿駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '歌舞伎町1-2-15 ソシアルビル１Ｆ',
                    'website' => 'https://g.co/kgs/KnhRvv',
                    'file_name' => 'okonomiyaki.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['お好み焼き'],
                    'name' => 'なんじゃもんじゃ',
                    'nearest_station' => '新宿三丁目駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '新宿3-7-5 一兆ビル　３Ｆ・４Ｆ',
                    'website' => 'https://maps.app.goo.gl/PuzmkzVEaJQRLpXcA',
                    'file_name' => 'okonomiyaki.jpg',
                ],
            ],
            'yakitori' => [
                1 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => '新宿 今井屋本店',
                    'nearest_station' => '新宿三丁目駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '新宿3-33-10 新宿モリエールビル B1F',
                    'website' => 'https://www.dd-holdings.jp/shops/imaiyahonten/shinjyuku',
                    'file_name' => 'yakitori.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => '俺のやきとり 銀座9丁目',
                    'nearest_station' => '新橋駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '新橋1-5-6 銀座第3誠和ビル B1F',
                    'website' => 'https://www.oreno.co.jp/restaurant/yakitori_ginza9',
                    'file_name' => 'yakitori.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => 'おもてなしとりよし 西新宿店',
                    'nearest_station' => '新宿駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '西新宿1-10-2 110ビル 11F',
                    'website' => 'https://sfpdining.jp/brand/omotenashi_toriyoshi/',
                    'file_name' => 'yakitori.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => '佐五右衛門 西新宿店',
                    'nearest_station' => '西武新宿駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '西新宿7-15-17 井西ビル 1F',
                    'website' => 'https://goodspiral.jp/restaurant/',
                    'file_name' => 'yakitori.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => '焼鳥つかだ 中目黒',
                    'nearest_station' => '中目黒駅',
                    'prefecture' => '東京都',
                    'city' => '目黒区',
                    'street' => '上目黒1-20-5 エーワンビル 1F',
                    'website' => 'https://www.yakitori-tsukada.jp/',
                    'file_name' => 'yakitori.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => 'SAGOEMON末代',
                    'nearest_station' => '渋谷駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '道玄坂2-6-12 道玄坂トロワービル 3F',
                    'website' => 'https://goodspiral.jp/restaurant/matsudai/',
                    'file_name' => 'yakitori.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => '串焼き もんじろう',
                    'nearest_station' => '恵比寿駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '恵比寿1-11-5 ジェムズ恵比寿 4F',
                    'website' => 'https://goodspiral.jp/restaurant/monjirou/',
                    'file_name' => 'yakitori.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => '炭火焼鳥 塚田農場 新宿東口駅前店',
                    'nearest_station' => '新宿西口駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '新宿3-23-2 新宿サンビル B1',
                    'website' => 'https://lp.tsukadanojo.jp/yakitori/',
                    'file_name' => 'yakitori.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => '山鶏 湯島本店',
                    'nearest_station' => '湯島駅',
                    'prefecture' => '東京都',
                    'city' => '文京区',
                    'street' => '湯島3丁目38-10 ハニービル３Ｆ',
                    'website' => 'https://yamadori-honten.com/',
                    'file_name' => 'yakitori.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['焼き鳥'],
                    'name' => '恵比寿 希鳥',
                    'nearest_station' => '恵比寿駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '恵比寿西1-2-7 恵比寿U・Kビル B1F',
                    'website' => 'http://kicho.jp/',
                    'file_name' => 'yakitori.jpg',
                ],
            ],
            'riceBall' => [
                1 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => 'おにぎり ぼんご',
                    'nearest_station' => '大塚駅',
                    'prefecture' => '東京都',
                    'city' => '豊島区',
                    'street' => '北大塚2-26-3 金田ビル 1F',
                    'website' => 'http://www.onigiribongo.info/',
                    'file_name' => 'riceBall.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => 'おにぎりのさんかく山',
                    'nearest_station' => '荻窪駅',
                    'prefecture' => '東京都',
                    'city' => '杉並区',
                    'street' => '荻窪5-29-9',
                    'website' => 'http://www.kuishinbo.jp/tenpo/detail.php?sankakuyama',
                    'file_name' => 'riceBall.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => 'おにぎり浅草宿六',
                    'nearest_station' => '浅草駅',
                    'prefecture' => '東京都',
                    'city' => '台東区',
                    'street' => '浅草3-9-10',
                    'website' => 'http://onigiriyadoroku.com/',
                    'file_name' => 'riceBall.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => '利さく',
                    'nearest_station' => '千駄木駅',
                    'prefecture' => '東京都',
                    'city' => '文京区',
                    'street' => '千駄木2-31-6',
                    'website' => 'https://www.risaku-tokyo.com/',
                    'file_name' => 'riceBall.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => 'Onigily Cafe',
                    'nearest_station' => '中目黒駅',
                    'prefecture' => '東京都',
                    'city' => '目黒区',
                    'street' => '中目黒3-1-4 山の手コーポ 1F',
                    'website' => 'http://www.onigily.com/',
                    'file_name' => 'riceBall.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => 'おむすびのGABA 秋葉原店',
                    'nearest_station' => '末広町駅',
                    'prefecture' => '東京都',
                    'city' => '千代田区',
                    'street' => '外神田4-7-2 サタケ東京本社ビル 1Ｆ',
                    'website' => 'https://www.kichiri.co.jp/shop/omusubi-gaba/074/',
                    'file_name' => 'riceBall.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => 'おだむすび 本店',
                    'nearest_station' => '新宿駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '西新宿1-1-3 小田急線新宿駅西口地下改札口横',
                    'website' => 'https://www.odakyu-restaurant.jp/shop/odamusubi/honten.html',
                    'file_name' => 'riceBall.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => '五穀豊穣 蔵一',
                    'nearest_station' => '羽田空港第１ターミナル駅',
                    'prefecture' => '東京都',
                    'city' => '大田区',
                    'street' => '羽田空港3-3-2 羽田空港第1旅客ターミナル 2',
                    'website' => 'https://www.airport-restaurant.com/restaurant-shop/kuraichi/',
                    'file_name' => 'riceBall.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => '汁や 東京ミッドタウン店',
                    'nearest_station' => '乃木坂駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '赤坂9-7-4 東京ミッドタウンガレリア B1F',
                    'website' => 'http://www.kayanoya.com/shop/shiruya/',
                    'file_name' => 'riceBall.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['おにぎり'],
                    'name' => 'おにぎり屋 丸豊',
                    'nearest_station' => '築地市場駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '築地4-9-9 築地場外',
                    'website' => 'https://www.tsukiji.or.jp/shoplist/cat-d/cat-15/389/',
                    'file_name' => 'riceBall.jpg',
                ],
            ],
            'syabusyabu' => [
                1 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => '東京肉しゃぶ家',
                    'nearest_station' => '東新宿駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '大久保1-12-3 カーサ第二新宿 1F',
                    'website' => 'http://tokyonikushabuya.com/',
                    'file_name' => 'syabusyabu.jpg',
                ],
                2 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => '代々木 今半',
                    'nearest_station' => '南新宿駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '代々木1-45-4 代々木山陽ビル B1F',
                    'website' => 'http://www.suntory.co.jp/gourmet/shop/0333708565/',
                    'file_name' => 'syabusyabu.jpg',
                ],
                3 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => 'かがやき',
                    'nearest_station' => '三ノ輪駅',
                    'prefecture' => '東京都',
                    'city' => '台東区',
                    'street' => '竜泉2-16-6',
                    'website' => 'https://www.facebook.com/profile.php?id=100094508118525',
                    'file_name' => 'syabusyabu.jpg',
                ],
                4 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => 'ざくろ 銀座店',
                    'nearest_station' => '銀座駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '銀座4-6-1 銀座三和ビル　Ｂ１Ｆ',
                    'website' => 'https://www.zakuro.co.jp/restaurant/ginza/index.html',
                    'file_name' => 'syabusyabu.jpg',
                ],
                5 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => 'かがやき',
                    'nearest_station' => '東銀座駅',
                    'prefecture' => '東京都',
                    'city' => '中央区',
                    'street' => '銀座1-20-2 1F・2',
                    'website' => 'https://www.kagayakiniku.com/',
                    'file_name' => 'syabusyabu.jpg',
                ],
                6 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => '別邸 壽',
                    'nearest_station' => '池袋駅',
                    'prefecture' => '東京都',
                    'city' => '豊島区',
                    'street' => '池袋1-1-7 第二伊三美ビル B1F',
                    'website' => 'https://ggv2303.gorp.jp/',
                    'file_name' => 'syabusyabu.jpg',
                ],
                7 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => 'ざくろ TBS店',
                    'nearest_station' => '赤坂駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '赤坂5-3-1 赤坂Bizタワー SHOPS＆DINING 2F',
                    'website' => 'https://www.zakuro.co.jp/restaurant/akasakabiz/index.html',
                    'file_name' => 'syabusyabu.jpg',
                ],
                8 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => '松阪牛 よし田',
                    'nearest_station' => '初台駅',
                    'prefecture' => '東京都',
                    'city' => '新宿区',
                    'street' => '西新宿3-20-2 東京オペラシティタワー 53階',
                    'website' => 'https://matsusakaushi-yoshida.jp/',
                    'file_name' => 'syabusyabu.jpg',
                ],
                9 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => 'シャングリラズシークレット 六本木店',
                    'nearest_station' => '六本木駅',
                    'prefecture' => '東京都',
                    'city' => '港区',
                    'street' => '六本木4-11-11 六本木GMビル 4F',
                    'website' => 'http://www.shangrila.jp/',
                    'file_name' => 'syabusyabu.jpg',
                ],
                10 => [
                    'rank_id' => $rankIds['しゃぶしゃぶ'],
                    'name' => 'しゃぶ膳紫波',
                    'nearest_station' => '明治神宮前駅',
                    'prefecture' => '東京都',
                    'city' => '渋谷区',
                    'street' => '神宮前5-17-11',
                    'website' => 'https://www.shabuzenshiwa.com/',
                    'file_name' => 'syabusyabu.jpg',
                ],
            ],
        ];

        foreach ($insertData as $genreName => $values) {
            foreach ($values as $rank => $value) {
                $restaurant = new Restaurant();
                $insert = array_merge($value, ['rank' => $rank]);
                $restaurant->fill($insert);
                $restaurant->save();
            }
        }
    }
}
